### ISSUE TITLE
GrabarVideo

### ISSUE THREAD

**Issue by Kuroval** [ftp-andrei/GrupoUnown#12]
Grabar el vídeo a subir por el equipo.

**Comment by TRdeXtremiana** [comment]
El video en sí lo tenemos, pero es muy largo, llevo desde ayer cortandolo y comprimiendolo:
https://drive.google.com/file/d/17GqoaiA6ugpZsvhM551Cx7GSQKuL4F2M/view?usp=share_link

**Comment by TRdeXtremiana** [comment]
![image](https://user-images.githubusercontent.com/98778132/205487422-678569fe-4332-463c-b5b2-c3f18afa64ec.png)

![image](https://user-images.githubusercontent.com/98778132/205487441-b3fd2b86-6c9f-49b9-a6ab-6aa01300adf2.png)
