### ISSUE TITLE
HTMLHome

### ISSUE THREAD

**Issue by Kuroval** [ftp-andrei/GrupoUnown#9]
Realizar HTML Home

**Comment by DanielAlonsoDAW** [comment]
Al pasarlo por https://validator.w3.org/nu/#file

Se ven varios errores, además veo que falta el footer.


El Nav tendría que quedar así: 

    <nav>
      <ul>
          <li> <a href="#">Home</a></li>
          <li><a href="podcast.html">Podcast</a></li>
          <li><a href="video.html">Vídeo</a></li>
      </ul>
    </nav>

Las tres etiquetas que autogenera VSCode, hay que quitarles el / antes del >
